//! The override cyamus appends as the last `-f` of a worktree stack.
//!
//! It is YAML whose values are JSON taken from the resolved model (JSON is
//! valid YAML flow syntax): only keys and the `!override` tags are written by
//! hand, so nothing from the user's files is ever re-interpreted.

use std::collections::BTreeSet;
use std::fmt::Write;

use serde_json::{Map, Value};

use super::model::Model;

/// Profile that keeps shadowed services from starting.
pub const SHADOW_PROFILE: &str = "cyamus-shadowed";
/// Key under which the worktree's cyamus network is declared.
pub const NETWORK_KEY: &str = "cyamus-net";

/// Builds the override, or `None` when there is nothing to add (no shared
/// stack, so no network and nothing shadowed).
pub fn worktree_override(
    model: &Model,
    shadowed: &BTreeSet<String>,
    network: Option<&str>,
) -> Option<String> {
    if network.is_none() && shadowed.is_empty() {
        return None;
    }
    let mut out =
        String::from("# Generated by `cyamus compose`; rewritten on every run.\nservices:\n");
    for (name, service) in &model.services {
        let mut body = String::new();
        if shadowed.contains(name) {
            writeln!(
                body,
                "    profiles: [{}]",
                json(&Value::from(SHADOW_PROFILE))
            )
            .unwrap();
        } else {
            if service.depends_on.keys().any(|d| shadowed.contains(d)) {
                let kept: Map<String, Value> = service
                    .depends_on
                    .iter()
                    .filter(|(d, _)| !shadowed.contains(*d))
                    .map(|(d, v)| (d.clone(), v.clone()))
                    .collect();
                writeln!(
                    body,
                    "    depends_on: !override {}",
                    json(&Value::Object(kept))
                )
                .unwrap();
            }
            if let (Some(_), None) = (network, &service.network_mode) {
                let mut networks = service
                    .networks
                    .clone()
                    .unwrap_or_else(|| Map::from_iter([("default".to_owned(), Value::Null)]));
                networks.insert(NETWORK_KEY.to_owned(), Value::Null);
                writeln!(
                    body,
                    "    networks: !override {}",
                    json(&Value::Object(networks))
                )
                .unwrap();
            }
        }
        if !body.is_empty() {
            writeln!(out, "  {}:", json(&Value::from(name.as_str()))).unwrap();
            out.push_str(&body);
        }
    }
    if let Some(network) = network {
        let decl = serde_json::json!({ "name": network, "external": true });
        writeln!(
            out,
            "networks:\n  {}: {}",
            json(&Value::from(NETWORK_KEY)),
            json(&decl)
        )
        .unwrap();
    }
    Some(out)
}

fn json(value: &Value) -> String {
    serde_json::to_string(value).expect("JSON values always serialize")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compose::model;

    fn model() -> Model {
        model::parse(
            r#"{"services": {
              "web": {"networks": {"default": null},
                      "depends_on": {"db": {"condition": "service_started", "required": true, "restart": false},
                                     "cache": {"condition": "service_healthy", "required": true, "restart": false}}},
              "cache": {"networks": {"default": null}},
              "worker": {"networks": {"backend": {"aliases": ["jobs"]}}},
              "hostnet": {"network_mode": "host"},
              "db": {"networks": {"default": null}}
            }}"#,
        )
        .unwrap()
    }

    fn shadow(names: &[&str]) -> BTreeSet<String> {
        names.iter().map(|n| (*n).to_owned()).collect()
    }

    #[test]
    fn nothing_to_do_without_shared_stack() {
        assert_eq!(worktree_override(&model(), &BTreeSet::new(), None), None);
    }

    #[test]
    fn shadowing_and_network() {
        let out =
            worktree_override(&model(), &shadow(&["db"]), Some("cyamus-myproj-feat-x")).unwrap();
        assert_eq!(
            out,
            "# Generated by `cyamus compose`; rewritten on every run.\n\
             services:\n  \
               \"cache\":\n    \
                 networks: !override {\"cyamus-net\":null,\"default\":null}\n  \
               \"db\":\n    \
                 profiles: [\"cyamus-shadowed\"]\n  \
               \"web\":\n    \
                 depends_on: !override {\"cache\":{\"condition\":\"service_healthy\",\"required\":true,\"restart\":false}}\n    \
                 networks: !override {\"cyamus-net\":null,\"default\":null}\n  \
               \"worker\":\n    \
                 networks: !override {\"backend\":{\"aliases\":[\"jobs\"]},\"cyamus-net\":null}\n\
             networks:\n  \
               \"cyamus-net\": {\"external\":true,\"name\":\"cyamus-myproj-feat-x\"}\n"
        );
        assert!(
            !out.contains("hostnet"),
            "network_mode services are left alone"
        );
    }

    #[test]
    fn missing_networks_mean_default() {
        let m = model::parse(r#"{"services": {"x": {}}}"#).unwrap();
        let out = worktree_override(&m, &BTreeSet::new(), Some("n")).unwrap();
        assert!(
            out.contains("\"x\":\n    networks: !override {\"cyamus-net\":null,\"default\":null}")
        );
    }

    #[test]
    fn hostile_names_are_quoted() {
        let m = model::parse(r#"{"services": {"we\"ird: name": {}}}"#).unwrap();
        let out = worktree_override(&m, &BTreeSet::new(), Some("n")).unwrap();
        assert!(out.contains("  \"we\\\"ird: name\":\n"));
    }
}
